### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by BryceLegendzPlayz** [PizzaLovers007/AdofaiTweaks#24]
How do I save stats in key viewer

**Comment by PizzaLovers007** [comment]
I don't have any plans to add this since I want to keep the mod simple. However, you could use a different KeyViewer mod that has a lot more functionality. The latest version is v3.6.1 from the ADOFAI.gg discord server: https://cdn.discordapp.com/attachments/886661471533162526/1062418162831867914/KeyViewer.zip

If you're interested in more mods, you can join here: https://discord.gg/adofaigg
